manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: medoix
      revision: "head:mikoto_7_1_0"
      import: app/west.yml
  self:
    path: config
