name: "Corne Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/corne.yml
    - corne/**

jobs:
  corne:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: corne/corne.yaml
      config_path: corne
      archive_name: corne-firmware
