name: "Corne Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/corne.yml
    - corne/**

jobs:
  corne-build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: corne/corne.yaml
      config_path: corne
      archive_name: corne-firmware

  corne-store:
    needs: corne-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: corne
        merge-multiple: true
    - uses: sylvanld/action-storage@v1
      with:
        src: corne
        dst: ./
        storage-branch: main