name: "Corne Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/corne.yml
    - config/corne*
    - corne/**

jobs:
  corne:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
      build_matrix_path: corne/corne.yaml
