name: "Lily58 Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/lily58.yml
    - lily58/**

jobs:
  lily58:
    runs-on: ubuntu-latest
    steps:
      - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          build_matrix_path: lily58/lily58.yaml
          config_path: lily58
          archive_name: lily58-firmware
      - uses: sylvanld/action-storage@v1
        with:
          src: lily58
          dst: ./
          storage-branch: main
